#!/bin/sh

_APP_ID=org.fcitx.Fcitx5

if ! $(flatpak info $_APP_ID &> /dev/null); then
  echo "$0: $_APP_ID was not found!"
  exit 1
fi
exec flatpak run --command=/app/libexec/fcitx5-wayland-launcher $_APP_ID "$@"
