#!/bin/sh

exec_swaybar() {
  echo swaybar > $XDG_RUNTIME_DIR/sway/barid
  exec swaybar "$@" &>/dev/null
}

exec_waybar() {
  echo waybar > $XDG_RUNTIME_DIR/sway/barid
  which waybar &>/dev/null &&
    exec waybar "$@" &>/dev/null
  which com.github.alexays.waybar &>/dev/null &&
    exec com.github.alexays.waybar "$@" &>/dev/null
}

exec_yambar() {
  echo yambar > $XDG_RUNTIME_DIR/sway/barid
  which yambar &>/dev/null &&
    exec yambar "$@" &>/dev/null
}

case "$XDG_STATUSBAR" in
  waybar)
    exec_waybar
    ;;
  yambar)
    exec_waybar
    ;;
  swaybar)
    exec_waybar
    ;;
esac

# default order
exec_waybar
exec_swaybar
exec_yambar
exit 1
