#!/bin/bash -e

while read -r line; do
    if [[ "$line" == 'usr/lib/modules/'+([^/])'/pkgbase' ]]; then
        read -r pkgbase < "/${line}"
        [ "${pkgbase}" = linux ] && pkgbase=linux-latest

        rm -f /"${line%'/pkgbase'}/initrd"

        # /boot only exist on legacy os
        [ -f "/boot/vmlinuz-${pkgbase}" ] &&
          rm -f "/boot/vmlinuz-${pkgbase}"
        [ -f "/boot/initramfs-${pkgbase}.img" ] &&
          rm -f "/boot/initramfs-${pkgbase}.img"
    fi
    if [[ "$line" == 'usr/lib/firmware/'+([^/])'-ucode/'+([^/])'-ucode.img' ]]; then
        # /boot only exist on legacy os
        [ -f /boot/$(basename $line) ] &&
          rm -f /boot/$(basename $line)
    fi
done
