# new package version
post_install() {
  echo "Find additional documentation about scanner driver install at:"
  echo "http://welcome.solutions.brother.com/bsc/public_s/id/linux/en/instruction_scn1.html"
  echo "For a network installation run the following as root:"
  echo "brsaneconfig4 -a name=\"Brother\" model=\"YOURMODELHERE\" ip=YOUR.SCANNER.IP.HERE"
  #/usr/opt/brother/scanner/brscan4/setupSaneScan4 -i
}
