#!/bin/bash

unset kbd
kbd=$(swaymsg -t get_inputs | jq -r '.[] | select (.type=="keyboard").xkb_active_layout_name'|head -1)

if [[ "$kbd" == *"("*")" ]]; then
  kbd="${kbd:${#kbd}-3:2}"
else
  kbd="${kbd:0:2}"
fi
echo ${kbd,,}
